import admin from "firebase-admin";
import fs from "fs";

// Read from .env.local
const envFile = fs.readFileSync(".env.local", "utf8");
const envVars = {};
envFile.split("\n").forEach(line => {
    const [key, ...val] = line.split("=");
    if (key && val) {
        let value = val.join("=").trim();
        if (value.startsWith('"') && value.endsWith('"')) {
            value = value.substring(1, value.length - 1);
        }
        envVars[key.trim()] = value.replace(/\\n/g, "\n");
    }
});

admin.initializeApp({
  credential: admin.credential.cert({
    projectId: envVars["FIREBASE_PROJECT_ID"],
    clientEmail: envVars["FIREBASE_CLIENT_EMAIL"],
    privateKey: envVars["FIREBASE_PRIVATE_KEY"],
  }),
});

const db = admin.firestore();

async function main() {
  const rosterRef = db.collection("topguild-system").doc("roster");
  const rosterDoc = await rosterRef.get();
  let rosterData = {};
  if (rosterDoc.exists) {
    const raw = rosterDoc.data();
    rosterData = raw?.data ? raw.data : raw;
  }

  let totalRemoved = 0;
  let totalRemaining = 0;
  let updatedRoster = {};

  for (const [job, members] of Object.entries(rosterData)) {
    if (Array.isArray(members)) {
      const filtered = members.filter(m => {
        // We look for discordId generated by our script: manual_1234567890_abc123
        const isRecentExcelImport = m.discordId && typeof m.discordId === "string" && m.discordId.match(/^manual_\d+_[a-z0-9]+$/);
        if (isRecentExcelImport) {
            console.log(`Removing ${m.name} (Job: ${job}) - ID: ${m.discordId}`);
            totalRemoved++;
            return false;
        }
        return true;
      });
      totalRemaining += filtered.length;
      updatedRoster[job] = filtered;
    } else {
        updatedRoster[job] = members;
    }
  }

  console.log(`Total removed: ${totalRemoved}`);
  console.log(`Total remaining in roster: ${totalRemaining}`);

  // Apply changes
  await rosterRef.set(updatedRoster);
  console.log("Database updated successfully.");
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
